/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Content;

import com.toedter.calendar.JDateChooser;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author tfaja
 */
public class CreateData extends javax.swing.JPanel {
    
    public Statement st;
    public ResultSet rs;
    Connection cn = koneksi.KoneksiDB.BukaKoneksi();
    
    public CreateData() {
        initComponents();
        Tampildata();
    }
    
    
    private void Tampildata() {
        try{
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM kamar");
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("No");
            model.addColumn("Kode Kamar");
            model.addColumn("Status");
            model.addColumn("Fasilitas");
            model.addColumn("Harga");
            
            int no = 1;

            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);

            while (rs.next()) {
                // Mendapatkan nilai status_kamar dari hasil query
                

                Object[] data = {
                    no++,
                    rs.getInt("kode_kamar"),
                    rs.getString("status"),
                    rs.getString("tipe_kamar"),  // Menggunakan string fasilitas yang telah ditentukan
                    rs.getDouble("harga"),
                };
                model.addRow(data);
                TbldataKamar.setModel(model);
            }
        } catch (Exception e) {
            e.printStackTrace(); 
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L_System_Check_in_Hotel = new javax.swing.JLabel();
        L_Input_data_kamar = new javax.swing.JLabel();
        L_No_kamar = new javax.swing.JLabel();
        L_Nama_tamu = new javax.swing.JLabel();
        TfnoKamar = new javax.swing.JTextField();
        TfTamu = new javax.swing.JTextField();
        btncheckin = new javax.swing.JButton();
        L_Data_kamar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbldataKamar = new javax.swing.JTable();
        L_CheckIn = new javax.swing.JLabel();
        jCheckIn = new com.toedter.calendar.JDateChooser();
        L_CheckOut = new javax.swing.JLabel();
        jCheckOut = new com.toedter.calendar.JDateChooser();
        L_Total_Hari = new javax.swing.JLabel();
        TfHari = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        L_System_Check_in_Hotel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_System_Check_in_Hotel.setText("System Check in Hotel");

        L_Input_data_kamar.setText("Input data kamar :");

        L_No_kamar.setText("No Kamar");

        L_Nama_tamu.setText("Nama Tamu");

        TfnoKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfnoKamarActionPerformed(evt);
            }
        });

        TfTamu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfTamuActionPerformed(evt);
            }
        });

        btncheckin.setText("Check in");
        btncheckin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheckinActionPerformed(evt);
            }
        });

        L_Data_kamar.setText("Data kamar :");

        TbldataKamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Kode Kamar", "Status", "Fasilitas", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TbldataKamar);

        L_CheckIn.setText("Check In");

        L_CheckOut.setText("Check Out");

        L_Total_Hari.setText("Total Hari");

        TfHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfHariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(L_System_Check_in_Hotel, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L_Data_kamar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(L_No_kamar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(TfnoKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btncheckin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(L_Nama_tamu, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TfTamu, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(L_CheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(L_CheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCheckOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(L_Total_Hari, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TfHari, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(L_Input_data_kamar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(L_System_Check_in_Hotel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(L_Input_data_kamar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_No_kamar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfnoKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_Nama_tamu, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfTamu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_Total_Hari, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(L_CheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(L_CheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btncheckin)
                .addGap(18, 18, 18)
                .addComponent(L_Data_kamar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TfnoKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfnoKamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfnoKamarActionPerformed

    private void TfTamuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfTamuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfTamuActionPerformed

    private void btncheckinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheckinActionPerformed
        // TODO add your handling code here:
        String noKamarText = TfnoKamar.getText();
        String namaTamu = TfTamu.getText();
        String totalHari = TfHari.getText();
        Date checkIn = jCheckIn.getDate();
        Date checkOut = jCheckOut.getDate();
        
        Double hari = Double.parseDouble(totalHari);
        int noKamar = Integer.parseInt(noKamarText);
        
        try {
            Connection cn = koneksi.KoneksiDB.BukaKoneksi();

            // Query untuk mendapatkan harga
            String queryHarga = "SELECT harga FROM kamar WHERE kode_kamar = ?";
            PreparedStatement pstHarga = cn.prepareStatement(queryHarga);
            pstHarga.setInt(1, noKamar);
            ResultSet rsHarga = pstHarga.executeQuery();

            // Memeriksa apakah ada hasil
            if (rsHarga.next()) {
                double price = rsHarga.getDouble("harga");

                // Query untuk menyimpan data pada tabel tamu
                String queryTamu = "INSERT INTO tamu (kode_kamar, nama) VALUES (?, ?)";
                PreparedStatement pstTamu = cn.prepareStatement(queryTamu, Statement.RETURN_GENERATED_KEYS);
                pstTamu.setInt(1, noKamar);
                pstTamu.setString(2, namaTamu);

                // Menjalankan query pertama
                int affectedRows = pstTamu.executeUpdate();

                // Mendapatkan nilai id_tamu yang baru saja diinsert
                if (affectedRows > 0) {
                    ResultSet generatedKeys = pstTamu.getGeneratedKeys();
                    if (generatedKeys.next()) {
                        int idTamu = generatedKeys.getInt(1);
                        double totalHarga = hari * price;

                        // Query untuk menyimpan data pada tabel reservasi
                        String queryReservasi = "INSERT INTO reservasi (kode_kamar, id_tamu, check_in, check_out, total_harga) VALUES (?, ?, ?, ?, ?)";
                        PreparedStatement pstReservasi = cn.prepareStatement(queryReservasi);
                        pstReservasi.setInt(1, noKamar);
                        pstReservasi.setInt(2, idTamu);

                        // Konversi java.util.Date ke java.sql.Date
                        java.sql.Date sqlCheckIn = new java.sql.Date(checkIn.getTime());
                        java.sql.Date sqlCheckOut = new java.sql.Date(checkOut.getTime());

                        pstReservasi.setDate(3, sqlCheckIn);
                        pstReservasi.setDate(4, sqlCheckOut);
                        pstReservasi.setDouble(5, totalHarga);

                        // Menjalankan query kedua
                        pstReservasi.executeUpdate();

                        // Menutup statement reservasi
                        pstReservasi.close();
                    }
                }

                // Menutup statement tamu dan harga
                pstTamu.close();
            }

            // Menutup koneksi
            cn.close();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btncheckinActionPerformed

    private void TfHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfHariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfHariActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_CheckIn;
    private javax.swing.JLabel L_CheckOut;
    private javax.swing.JLabel L_Data_kamar;
    private javax.swing.JLabel L_Input_data_kamar;
    private javax.swing.JLabel L_Nama_tamu;
    private javax.swing.JLabel L_No_kamar;
    private javax.swing.JLabel L_System_Check_in_Hotel;
    private javax.swing.JLabel L_Total_Hari;
    private javax.swing.JTable TbldataKamar;
    private javax.swing.JTextField TfHari;
    private javax.swing.JTextField TfTamu;
    private javax.swing.JTextField TfnoKamar;
    private javax.swing.JButton btncheckin;
    private com.toedter.calendar.JDateChooser jCheckIn;
    private com.toedter.calendar.JDateChooser jCheckOut;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
